---
- name: config | Ensuring Guacamole Folders Exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rwx,g=rx,o=rx
  become: true
  with_items:
    - /etc/guacamole
    - /etc/guacamole/lib
    - /etc/guacamole/extensions

- name: config | Configuring guacd
  ansible.builtin.template:
    src: etc/guacamole/guacd.conf.j2
    dest: /etc/guacamole/guacd.conf
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - kill guacd
    - restart guacd
  when: guacd_config is defined

- name: config | Configuring guacamole.properties
  ansible.builtin.template:
    src: etc/guacamole/guacamole.properties.j2
    dest: /etc/guacamole/guacamole.properties
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd

- name: config | Configuring user-mapping.xml
  ansible.builtin.template:
    src: etc/guacamole/user-mapping.xml.j2
    dest: /etc/guacamole/user-mapping.xml
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd
  when: guacamole_users is defined and guacamole_users | list | length >= 1

- name: config | Downloading Auth JDBC Library
  ansible.builtin.unarchive:
    src: "{{ guacamole_dl_url + '/binary/' + guacamole_auth_jdbc_package }}"
    dest: "{{ guacamole_src_dir }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth or guacamole_postgresql_auth

- name: config | Copying Auth JDBC Connector # noqa risky-file-permissions
  ansible.builtin.copy:
    src: "{{ guacamole_src_dir + '/' + 'guacamole-auth-jdbc-' + guacamole_version + '/mysql/' + 'guacamole-auth-jdbc-mysql-' + guacamole_version + '.jar' }}"
    dest: /etc/guacamole/extensions/
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth

- name: config | Copying Auth JDBC Connector # noqa risky-file-permissions
  ansible.builtin.copy:
    src: "{{ guacamole_src_dir + '/' + 'guacamole-auth-jdbc-' + guacamole_version + '/postgresql/' + 'guacamole-auth-jdbc-postgresql-' + guacamole_version + '.jar' }}"
    dest: /etc/guacamole/extensions/
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    remote_src: true
  become: true
  when: guacamole_postgresql_auth

- name: config | Downloading MySQL Connector
  ansible.builtin.unarchive:
    src: "{{ guacamole_mysql_connector_package }}"
    dest: "{{ guacamole_src_dir }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth

- name: config | Copying MySQL Connector # noqa risky-file-permissions
  ansible.builtin.copy:
    src: "{{ guacamole_src_dir + '/' + 'mysql-connector-j-' + guacamole_mysql_connector_version + '/' + 'mysql-connector-j-' + guacamole_mysql_connector_version + '.jar' }}"
    dest: /etc/guacamole/lib/
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth

- name: config | Downloading PostgreSQL Connector # noqa risky-file-permissions
  ansible.builtin.get_url:
    url: "{{ guacamole_postgresql_connector_package }}"
    dest: "{{ guacamole_src_dir }}"
  become: true
  when: guacamole_postgresql_auth

- name: config | Copying PostgreSQL Connector # noqa risky-file-permissions
  ansible.builtin.copy:
    src: "{{ guacamole_src_dir + '/' + 'postgresql-' + guacamole_postgresql_connector_version + '.jar' }}"
    dest: /etc/guacamole/lib/
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    remote_src: true
  become: true
  when: guacamole_postgresql_auth

- name: config | Downloading Auth OpenID Library
  ansible.builtin.unarchive:
    src: "{{ guacamole_dl_url + '/binary/' + guacamole_auth_openid_package }}"
    dest: "{{ guacamole_src_dir }}"
    remote_src: true
  become: true
  when: guacamole_openid_auth

- name: config | Copying Auth OpenID Connector # noqa risky-file-permissions
  ansible.builtin.copy:
    src: "{{ guacamole_src_dir + '/' + 'guacamole-auth-sso-' + guacamole_version + '/openid/' + 'guacamole-auth-sso-openid-' + guacamole_version + '.jar' }}"
    dest: "{{ '/etc/guacamole/extensions/' + guacamole_auth_openid_priority + 'guacamole-auth-sso-' + guacamole_version + '.jar' }}"
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    remote_src: true
  become: true
  when: guacamole_openid_auth

- name: config | list previous extensions version
  ansible.builtin.find:
    paths: "/etc/guacamole/extensions/"
    excludes: '*{{ guacamole_version }}*'
    file_type: file
  register: guacamole_previous_extensions

- name: config | Delete previous extensions version
  ansible.builtin.file:
    path: "{{ guacamole_extensions.path }}"
    state: absent
  loop: "{{ guacamole_previous_extensions.files }}"
  loop_control:
    loop_var: guacamole_extensions

- name: config | Checking If DB Has Been Populated
  ansible.builtin.stat:
    path: /etc/guacamole/.db_populated
  register: _guacamole_db_populated_check
  when: guacamole_mysql_auth or guacamole_postgresql_auth

- name: Install Mariadb-Client
  apt:
    name: python3-pymysql
  when: guacamole_mysql_auth

- name: config | Marking DB As Populated # noqa no-handler risky-file-permissions
  ansible.builtin.file:
    path: /etc/guacamole/.db_populated
    state: touch
  become: true
  when: >
    (guacamole_mysql_auth or
     guacamole_postgresql_auth)

- name: config | Creating Tomcat symlink For guacamole.properties
  ansible.builtin.file:
    src: /etc/guacamole
    dest: "{{ '/usr/share/' + guacamole_tomcat + '/.guacamole' }}"
    state: link
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd

- name: Update index.hmtl of ROOT in tomcat to redirect to guacamole webapps # noqa no-handler risky-file-permissions
  ansible.builtin.copy:
    content: "<meta http-equiv='Refresh' content=\"0; url='{{ guacamole_redirect }}'\"/>"
    dest: "{{ '/var/lib/' + guacamole_tomcat + '/webapps/ROOT/index.html' }}"
  when: guacamole_redirect is defined
  become: true
